"""Public delivery for GENERATED, licence-cleared site media -- and nothing else.

This is the only unauthenticated media route in the platform, so its scope is
deliberately tiny and every widening is a decision someone has to make on
purpose:

  * It serves ONE directory: <MEDIA_CACHE_DIR>/stock, which only media_sourcing
    ever writes to. Customer uploads and generated user media live in
    MEDIA_CACHE_DIR itself and are served by routes_media behind
    authentication + ownership; nothing here can reach them.
  * Identifiers are opaque 32-char uuid4 hex, generated by us. A request carries
    an id, never a path, so there is no filename, prefix or traversal sequence
    for an attacker to influence. Ids that do not match the pattern are refused
    before any filesystem call.
  * An asset is served only when its provenance sidecar says it is publishable:
    an acceptable licence state AND a public_url already assigned. Bytes sitting
    in the directory are not sufficient -- publication is an explicit act.
  * Only real image bytes are served: the stored content type must be on the
    allowlist and the bytes must still start with that type's magic number, so a
    file swapped on disk cannot become an HTML/SVG payload served from our
    origin.

Why a route at all: generated pages must not hotlink third-party images. Serving
the bytes ourselves keeps customer sites free of external runtime dependencies
and stops a provider outage (or tracker) reaching their visitors.
"""
from __future__ import annotations

import json
import logging
import os
import re
from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/assets", tags=["public-media"])

# The ONLY directory this route will ever read from.
STOCK_DIR = (Path(os.environ.get("MEDIA_CACHE_DIR",
                                 str(Path(__file__).resolve().parent / "media_cache")))
             / "stock")

# Opaque identifier shape: uuid4().hex, nothing else.
_ID_RE = re.compile(r"^[0-9a-f]{32}$")

_TYPES = {
    ".jpg": ("image/jpeg", b"\xff\xd8\xff"),
    ".jpeg": ("image/jpeg", b"\xff\xd8\xff"),
    ".png": ("image/png", b"\x89PNG\r\n\x1a\n"),
    ".webp": ("image/webp", None),          # checked via RIFF....WEBP below
}

# Long-lived and immutable: the id is generated per stored file and never reused,
# so the bytes behind a URL cannot change.
_CACHE_CONTROL = "public, max-age=31536000, immutable"
_SECURITY_HEADERS = {
    "X-Content-Type-Options": "nosniff",
    # The response is an image; forbid it being treated as anything active.
    "Content-Security-Policy": "default-src 'none'; sandbox",
    "Referrer-Policy": "no-referrer",
    # Customer sites are served from their own origins and must be able to embed.
    "Cross-Origin-Resource-Policy": "cross-origin",
}


def _magic_ok(path: Path, suffix: str) -> bool:
    """Re-verify on serve: stored metadata is not trusted over actual bytes."""
    expected = _TYPES.get(suffix, (None, None))[1]
    try:
        with path.open("rb") as fh:
            head = fh.read(16)
    except OSError:
        return False
    if suffix == ".webp":
        return head[:4] == b"RIFF" and head[8:12] == b"WEBP"
    return bool(expected) and head.startswith(expected)


def _resolve(asset_id: str, suffix: str) -> Path:
    """Map an opaque id to a file INSIDE the stock directory, or refuse.

    The containment check is done after resolution so a symlink planted in the
    directory cannot point outside it.
    """
    if not _ID_RE.match(asset_id or ""):
        raise HTTPException(status_code=404, detail="Not found")
    if suffix not in _TYPES:
        raise HTTPException(status_code=404, detail="Not found")

    base = STOCK_DIR.resolve()
    candidate = (base / f"{asset_id}{suffix}").resolve()
    try:
        candidate.relative_to(base)
    except ValueError:
        logger.warning("public media: refused path escaping the stock directory")
        raise HTTPException(status_code=404, detail="Not found")
    if not candidate.is_file():
        raise HTTPException(status_code=404, detail="Not found")
    return candidate


def _publishable(asset_id: str) -> dict:
    """The provenance sidecar must exist and mark this asset as publishable."""
    side = (STOCK_DIR.resolve() / f"{asset_id}.json")
    try:
        record = json.loads(side.read_text(encoding="utf-8"))
    except Exception:
        raise HTTPException(status_code=404, detail="Not found")

    state = str(record.get("provenance_state") or "")
    if state not in ("provider_declared", "verified"):
        # Present on disk, but not cleared for publication.
        raise HTTPException(status_code=404, detail="Not found")
    if not record.get("public_url"):
        raise HTTPException(status_code=404, detail="Not found")
    return record


@router.get("/{filename}")
async def serve_public_asset(filename: str):
    """Serve one licence-cleared generated image by opaque id."""
    # Split exactly once, from the right, and never touch the filesystem with
    # anything the caller supplied verbatim.
    if "." not in filename or "/" in filename or "\\" in filename:
        raise HTTPException(status_code=404, detail="Not found")
    stem, _dot, ext = filename.rpartition(".")
    suffix = f".{ext.lower()}"

    record = _publishable(stem)
    path = _resolve(stem, suffix)

    media_type = _TYPES[suffix][0]
    if str(record.get("content_type") or media_type) != media_type:
        raise HTTPException(status_code=404, detail="Not found")
    if not _magic_ok(path, suffix):
        logger.warning("public media: stored bytes failed the magic-byte re-check")
        raise HTTPException(status_code=404, detail="Not found")

    headers = dict(_SECURITY_HEADERS)
    headers["Cache-Control"] = _CACHE_CONTROL
    return FileResponse(str(path), media_type=media_type, headers=headers)


__all__ = ["router", "STOCK_DIR"]
